CREATE TABLE films (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    director VARCHAR(100) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    IMDB_rating DECIMAL(3,1) NOT NULL,
    release_year YEAR NOT NULL
);

INSERT INTO films (title,director,genre,IMDB_rating,release_year)
VALUES 
('The Matrix', 'Lana Wachowski, Lilly Wachowski', 'Action', 8.7, 1999),
('The Silence of the Lambs', 'Jonathan Demme', 'Thriller', 8.6, 1991),
('Goodfellas', 'Martin Scorsese', 'Crime', 8.7, 1990),
('Schindler\'s List', 'Steven Spielberg', 'Biography', 8.9, 1993),
('Se7en', 'David Fincher', 'Crime', 8.6, 1995),
('Gladiator', 'Ridley Scott', 'Action', 8.5, 2000),
('The Departed', 'Martin Scorsese', 'Crime', 8.5, 2006),
('The Prestige', 'Christopher Nolan', 'Drama', 8.5, 2006),
('The Shawshank Redemption', 'Frank Darabont', 'Drama', 9.3, 1994),
('The Godfather', 'Francis Ford Coppola', 'Crime', 9.2, 1972),
('The Dark Knight', 'Christopher Nolan', 'Action', 9.0, 2008),
('Pulp Fiction', 'Quentin Tarantino', 'Crime', 8.9, 1994),
('Forrest Gump', 'Robert Zemeckis', 'Drama', 8.8, 1994),
('Inception', 'Christopher Nolan', 'Action', 8.8, 2010),
('The Lord of the Rings: The Return of the King', 'Peter Jackson', 'Adventure', 8.9, 2003),
('The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 'Adventure', 8.8, 2001),
('The Lord of the Rings: The Two Towers', 'Peter Jackson', 'Adventure', 8.7, 2002),
('Fight Club', 'David Fincher', 'Drama', 8.8, 1999),
('The Green Mile', 'Frank Darabont', 'Crime', 8.6, 1999),
('The Usual Suspects', 'Bryan Singer', 'Crime', 8.5, 1995),
('Leon: The Professional', 'Luc Besson', 'Action', 8.5, 1994),
('Saving Private Ryan', 'Steven Spielberg', 'Drama', 8.6, 1998),
('The Pianist', 'Roman Polanski', 'Biography', 8.5, 2002),
('The Intouchables', 'Olivier Nakache, Éric Toledano', 'Biography', 8.5, 2011),
('The Lion King', 'Roger Allers, Rob Minkoff', 'Animation', 8.5, 1994),
('Back to the Future', 'Robert Zemeckis', 'Adventure', 8.5, 1985),
('The Terminator', 'James Cameron', 'Action', 8.0, 1984),
('Terminator 2: Judgment Day', 'James Cameron', 'Action', 8.5, 1991),
('The Godfather: Part II', 'Francis Ford Coppola', 'Crime', 9.0, 1974),
('Cats', 'Tom Hooper', 'Musical', 2.8, 2019),
('Birdemic: Shock and Terror', 'James Nguyen', 'Horror', 1.8, 2010),
('The Room', 'Tommy Wiseau', 'Drama', 3.7, 2003),
('Disaster Movie', 'Jason Friedberg, Aaron Seltzer', 'Comedy', 1.9, 2008),
('Superbabies: Baby Geniuses 2', 'Bob Clark', 'Family', 2.0, 2004),
('Jack and Jill', 'Dennis Dugan', 'Comedy', 3.3, 2011),
('Gigli', 'Martin Brest', 'Romance', 2.4, 2003),
('Battlefield Earth', 'Roger Christian', 'Sci-Fi', 2.5, 2000),
('Movie 43', 'Various', 'Comedy', 4.3, 2013),
('Catwoman', 'Pitof', 'Action', 3.4, 2004),
('The Last Airbender', 'M. Night Shyamalan', 'Action', 4.1, 2010),
('Batman & Robin', 'Joel Schumacher', 'Action', 3.7, 1997),
('Alone in the Dark', 'Uwe Boll', 'Horror', 2.4, 2005),
('The Hottie & the Nottie', 'Tom Putnam', 'Comedy', 1.9, 2008),
('The Love Guru', 'Marco Schnabel', 'Comedy', 3.8, 2008),
('The Emoji Movie', 'Tony Leondis', 'Animation', 3.3, 2017),
('House of the Dead', 'Uwe Boll', 'Horror', 2.0, 2003),
('Bucky Larson: Born to Be a Star', 'Tom Brady', 'Comedy', 3.3, 2011),
('Dirty Love', 'John Asher', 'Comedy', 3.5, 2005),
('Meet the Spartans', 'Jason Friedberg, Aaron Seltzer', 'Comedy', 2.8, 2008);